channels:
- bioconda
- conda-forge
- defaults
- ome
dependencies:
- pip
- idr-py
- scikit-image
- scikit-learn
- bokeh=2.2.*
- ipywidgets
- matplotlib
- numpy
- pandas
- seaborn
- tifffile
- jupyter_contrib_nbextensions
- intermine
